/**
 * Safety Threshold Evaluation
 *
 * Evaluates PRO responses and lab values against safety thresholds from the protocol.
 * All rules come from the Safety Agent output - NO HARDCODED RULES.
 */

import type { SafetyProAlert, SafetyLabThreshold } from '@/lib/agents/types'
import type { ProResponse } from './pro-submission'

export type AlertType = 'trigger_instrument' | 'coordinator_alert' | 'urgent_alert' | 'crisis_resources'

export interface SafetyAlert {
  type: AlertType
  condition: string
  message: string
  urgency?: string
  targetInstrument?: string
}

export interface SafetyEvaluationResult {
  alerts: SafetyAlert[]
  showCrisisResources: boolean
  triggerFollowUp: string | null
}

/**
 * Evaluate safety based on submission scores and responses.
 * Uses dynamic rules from protocol.safetyMonitoring.proAlerts (generated by Safety Agent).
 *
 * @param participantId - The participant ID (for logging)
 * @param instrumentId - The instrument being evaluated
 * @param scores - Calculated scores including total
 * @param responses - Individual question responses
 * @param proAlerts - Safety alerts from protocol (generated by Safety Agent)
 */
export async function evaluateSafety(
  participantId: string,
  instrumentId: string,
  scores: { total: number; [key: string]: number },
  responses: ProResponse[],
  proAlerts: SafetyProAlert[]
): Promise<SafetyEvaluationResult> {
  const alerts: SafetyAlert[] = []
  let showCrisisResources = false
  let triggerFollowUp: string | null = null

  // Build response lookup
  const responseMap: Record<string, number> = {}
  responses.forEach(r => {
    responseMap[r.questionId] = r.value
  })

  // Filter alerts for this instrument
  const relevantAlerts = proAlerts.filter(a => a.instrumentId === instrumentId)

  if (relevantAlerts.length === 0) {
    console.log(`[Safety] No alerts configured for instrument: ${instrumentId}`)
  }

  // Evaluate each alert rule
  for (const alertConfig of relevantAlerts) {
    if (evaluateCondition(alertConfig.condition, scores, responseMap)) {
      const alert: SafetyAlert = {
        type: alertConfig.type as AlertType,
        condition: alertConfig.condition,
        message: alertConfig.message,
        urgency: alertConfig.urgency || undefined,
      }

      if (alertConfig.type === 'trigger_instrument' && alertConfig.target) {
        alert.targetInstrument = alertConfig.target
        triggerFollowUp = alertConfig.target
      }

      if (alertConfig.type === 'crisis_resources') {
        showCrisisResources = true
      }

      alerts.push(alert)
      console.log(`[Safety] Alert triggered: ${alertConfig.type} for ${instrumentId} (${alertConfig.condition})`)
    }
  }

  return {
    alerts,
    showCrisisResources,
    triggerFollowUp,
  }
}

/**
 * Evaluate lab results against thresholds from protocol.
 * Uses dynamic thresholds from protocol.safetyMonitoring.labThresholds (generated by Safety Agent).
 *
 * @param labValue - The lab result value
 * @param labMarker - The lab marker name (e.g., "hematocrit", "psa")
 * @param labThresholds - Lab thresholds from protocol (generated by Safety Agent)
 */
export async function evaluateLabSafety(
  labValue: number,
  labMarker: string,
  labThresholds: SafetyLabThreshold[]
): Promise<SafetyAlert[]> {
  const alerts: SafetyAlert[] = []

  // Filter thresholds for this lab marker
  const relevantThresholds = labThresholds.filter(t =>
    t.marker.toLowerCase() === labMarker.toLowerCase()
  )

  if (relevantThresholds.length === 0) {
    console.log(`[Safety] No thresholds configured for lab marker: ${labMarker}`)
    return alerts
  }

  for (const threshold of relevantThresholds) {
    let triggered = false

    switch (threshold.operator) {
      case '>': triggered = labValue > threshold.value; break
      case '<': triggered = labValue < threshold.value; break
      case '>=': triggered = labValue >= threshold.value; break
      case '<=': triggered = labValue <= threshold.value; break
      case '==': triggered = labValue === threshold.value; break
      case '!=': triggered = labValue !== threshold.value; break
    }

    if (triggered) {
      alerts.push({
        type: threshold.type,
        condition: `${labMarker} ${threshold.operator} ${threshold.value}`,
        message: `${labMarker}: ${labValue} ${threshold.unit} - ${threshold.action}`,
        urgency: threshold.urgency,
      })
      console.log(`[Safety] Lab threshold triggered: ${threshold.type} for ${labMarker} (${labValue} ${threshold.operator} ${threshold.value})`)
    }
  }

  return alerts
}

/**
 * Evaluate a condition string against scores and responses
 * Supports: "total >= 3", "q9 > 0", "total < 5", "ae_severity >= 2"
 */
function evaluateCondition(
  condition: string,
  scores: { total: number; [key: string]: number },
  responseMap: Record<string, number>
): boolean {
  try {
    // Parse condition: "variable operator value"
    const match = condition.match(/^(\w+)\s*(>=|<=|>|<|==|!=)\s*(\d+)$/)
    if (!match) {
      console.warn(`[Safety] Invalid condition format: ${condition}`)
      return false
    }

    const [, variable, operator, valueStr] = match
    const threshold = parseInt(valueStr, 10)

    // Get the value to compare
    let value: number
    if (variable === 'total') {
      value = scores.total
    } else if (variable in scores) {
      value = scores[variable]
    } else if (variable in responseMap) {
      value = responseMap[variable]
    } else {
      // Try prefixed versions (e.g., q9 might be stored as phq9_q9)
      const prefixedKey = Object.keys(responseMap).find(k => k.endsWith(`_${variable}`))
      if (prefixedKey) {
        value = responseMap[prefixedKey]
      } else {
        console.warn(`[Safety] Unknown variable in condition: ${variable}`)
        return false
      }
    }

    // Evaluate
    switch (operator) {
      case '>=': return value >= threshold
      case '<=': return value <= threshold
      case '>': return value > threshold
      case '<': return value < threshold
      case '==': return value === threshold
      case '!=': return value !== threshold
      default: return false
    }
  } catch (error) {
    console.error(`[Safety] Error evaluating condition "${condition}":`, error)
    return false
  }
}

/**
 * Crisis resources content to display.
 * This is static content - the actual crisis protocol can be customized
 * per study via the Safety Agent output.
 */
export const CRISIS_RESOURCES = {
  title: "If you're having thoughts of harming yourself, please reach out for support:",
  resources: [
    {
      icon: '📞',
      name: 'National Suicide Prevention Lifeline',
      value: '988',
      type: 'phone',
    },
    {
      icon: '💬',
      name: 'Crisis Text Line',
      value: 'Text HOME to 741741',
      type: 'text',
    },
    {
      icon: '🏥',
      name: 'Emergency',
      value: 'Call 911 or go to your nearest ER',
      type: 'emergency',
    },
  ],
  footer: 'A member of our team will also be reaching out to you.',
}
